import type { Metadata } from "next";
import "./globals.css";
import "@fontsource/libre-franklin"; // Imports regular weight
import "@fontsource/libre-franklin/700.css"; // Imports bold weight
import "@fontsource/libre-franklin/400-italic.css"; // Imports italic weight
import MyCard from '@/components/MyCard';
import SideMenu from '@/components/SideMenu';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by thanawat sriwan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-dvw h-dvh font-sans flex justify-center bg-[#1D1C1D]">
        <div className="flex justify-between w-300 max-w-full h-full items-center relative">
          <div className="hidden sm:block">
            <MyCard />
          </div>
          <div className="w-245 max-w-full h-[695px] flex">
            {children}
            <div className="sm:w-[60px]"></div>
          </div>
          <div className="absolute right-0  duration-300">
            <SideMenu />
          </div>
        </div>
      </body>
    </html>
  );
}
